set(TCMALLOC_FILES
./tcmalloc/tc_wrappers.cc
./tcmalloc/allocation_sample.cc
./tcmalloc/allocation_sample.h
./tcmalloc/allocation_sampling.cc
./tcmalloc/allocation_sampling.h
./tcmalloc/alloc_at_least.cc
./tcmalloc/alloc_at_least.h
./tcmalloc/arena.cc
./tcmalloc/arena.h
./tcmalloc/background.cc
./tcmalloc/central_freelist.cc
./tcmalloc/central_freelist.h
./tcmalloc/common.cc
./tcmalloc/common.h
./tcmalloc/cpu_cache.cc
./tcmalloc/cpu_cache.h
./tcmalloc/deallocation_profiler.cc
./tcmalloc/deallocation_profiler.h
./tcmalloc/error_reporting.cc
./tcmalloc/error_reporting.h
./tcmalloc/experimental_pow2_size_class.cc
./tcmalloc/experiment.cc
./tcmalloc/experiment_config.h
./tcmalloc/experiment.h
./tcmalloc/global_stats.cc
./tcmalloc/global_stats.h
./tcmalloc/guarded_allocations.h
./tcmalloc/guarded_page_allocator.cc
./tcmalloc/guarded_page_allocator.h
./tcmalloc/hinted_tracker_lists.h
./tcmalloc/huge_address_map.cc
./tcmalloc/huge_address_map.h
./tcmalloc/huge_allocator.cc
./tcmalloc/huge_allocator.h
./tcmalloc/huge_cache.cc
./tcmalloc/huge_cache.h
./tcmalloc/huge_page_aware_allocator.cc
./tcmalloc/huge_page_aware_allocator.h
./tcmalloc/huge_page_filler.h
./tcmalloc/huge_pages.h
./tcmalloc/huge_page_subrelease.h
./tcmalloc/huge_region.h
./tcmalloc/internal_malloc_extension.h
./tcmalloc/internal_malloc_tracing_extension.h
./tcmalloc/legacy_size_classes.cc
./tcmalloc/libc_override.h
./tcmalloc/malloc_extension.cc
./tcmalloc/malloc_extension.h
./tcmalloc/malloc_hook.cc
./tcmalloc/malloc_hook.h
./tcmalloc/malloc_hook_invoke.h
./tcmalloc/malloc_tracing_extension.cc
./tcmalloc/malloc_tracing_extension.h
./tcmalloc/metadata_allocator.h
./tcmalloc/metadata_object_allocator.h
./tcmalloc/mock_central_freelist.cc
./tcmalloc/mock_central_freelist.h
./tcmalloc/mock_huge_page_static_forwarder.cc
./tcmalloc/mock_huge_page_static_forwarder.h
./tcmalloc/mock_metadata_allocator.h
./tcmalloc/mock_static_forwarder.h
./tcmalloc/mock_transfer_cache.cc
./tcmalloc/mock_transfer_cache.h
./tcmalloc/mock_virtual_allocator.h
./tcmalloc/new_extension.h
./tcmalloc/page_allocator.cc
./tcmalloc/page_allocator.h
./tcmalloc/page_allocator_interface.cc
./tcmalloc/page_allocator_interface.h
./tcmalloc/pagemap.cc
./tcmalloc/pagemap.h
./tcmalloc/pages.h
./tcmalloc/parameters.cc
./tcmalloc/parameters.h
./tcmalloc/peak_heap_tracker.cc
./tcmalloc/peak_heap_tracker.h
./tcmalloc/reuse_size_classes_v2.cc
./tcmalloc/sampler.cc
./tcmalloc/sampler.h
./tcmalloc/segv_handler.cc
./tcmalloc/segv_handler.h
./tcmalloc/size_class_info.h
./tcmalloc/size_classes.cc
./tcmalloc/sizemap.cc
./tcmalloc/sizemap.h
./tcmalloc/span.cc
./tcmalloc/span.h
./tcmalloc/span_stats.h
./tcmalloc/stack_trace_table.cc
./tcmalloc/stack_trace_table.h
./tcmalloc/static_vars.cc
./tcmalloc/static_vars.h
./tcmalloc/stats.cc
./tcmalloc/stats.h
./tcmalloc/tcmalloc.cc
./tcmalloc/tcmalloc.h
./tcmalloc/tcmalloc_policy.h
./tcmalloc/thread_cache.cc
./tcmalloc/thread_cache.h
./tcmalloc/transfer_cache.cc
./tcmalloc/transfer_cache.h
./tcmalloc/transfer_cache_internals.h
./tcmalloc/transfer_cache_stats.h
./tcmalloc/want_disable_dynamic_slabs.cc
./tcmalloc/want_disable_huge_region_more_often.cc
./tcmalloc/want_hpaa.cc
./tcmalloc/want_legacy_size_classes.cc
./tcmalloc/want_numa_aware.cc
)

set(TCMALLOC_INTERNAL_FILES
./tcmalloc/internal/affinity.cc
./tcmalloc/internal/affinity.h
./tcmalloc/internal/allocation_guard.cc
./tcmalloc/internal/allocation_guard.h
./tcmalloc/internal/atomic_danger.h
./tcmalloc/internal/atomic_stats_counter.h
./tcmalloc/internal/cache_topology.cc
./tcmalloc/internal/cache_topology.h
./tcmalloc/internal/clock.h
./tcmalloc/internal/config.h
./tcmalloc/internal/cpu_utils.h
./tcmalloc/internal/declarations.h
./tcmalloc/internal/environment.cc
./tcmalloc/internal/environment.h
./tcmalloc/internal/explicitly_constructed.h
./tcmalloc/internal/exponential_biased.h
./tcmalloc/internal/fake_profile.h
./tcmalloc/internal/gwp_asan_state.h
./tcmalloc/internal/hook_list.cc
./tcmalloc/internal/hook_list.h
./tcmalloc/internal/linked_list.h
./tcmalloc/internal/linux_syscall_support.h
./tcmalloc/internal/logging.cc
./tcmalloc/internal/logging.h
./tcmalloc/internal/memory_stats.cc
./tcmalloc/internal/memory_stats.h
./tcmalloc/internal/memory_tag.cc
./tcmalloc/internal/mincore.cc
./tcmalloc/internal/mincore.h
./tcmalloc/internal/mock_span.h
./tcmalloc/internal/numa.cc
./tcmalloc/internal/numa.h
./tcmalloc/internal/optimization.h
./tcmalloc/internal/overflow.h
./tcmalloc/internal/pageflags.cc
./tcmalloc/internal/pageflags.h
./tcmalloc/internal/page_size.cc
./tcmalloc/internal/page_size.h
./tcmalloc/internal/parameter_accessors.h
./tcmalloc/internal/percpu.cc
./tcmalloc/internal/percpu.h
./tcmalloc/internal/percpu_rseq_unsupported.cc
./tcmalloc/internal/percpu_rseq_x86_64.S
./tcmalloc/internal/percpu_tcmalloc.h
./tcmalloc/internal/prefetch.h
./tcmalloc/internal/proc_maps.cc
./tcmalloc/internal/proc_maps.h
./tcmalloc/internal/range_tracker.h
./tcmalloc/internal/residency.cc
./tcmalloc/internal/residency.h
./tcmalloc/internal/sampled_allocation.h
./tcmalloc/internal/sampled_allocation_recorder.h
./tcmalloc/internal/stacktrace_filter.h
./tcmalloc/internal/sysinfo.cc
./tcmalloc/internal/sysinfo.h
./tcmalloc/internal/system_allocator.cc
./tcmalloc/internal/system_allocator.h
./tcmalloc/internal/timeseries_tracker.h
./tcmalloc/internal/util.cc
./tcmalloc/internal/util.h
)
